version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns: ['*']
    commit-message:
      prefix: ci
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: deps
  - package-ecosystem: pip
    directory: /test
    schedule:
      interval: daily
    commit-message:
      prefix: deps
