windows_bin:
  stage: deploy
  image:
    name: batonogov/pyinstaller-windows:v4.2.6
    entrypoint: ['']
  script:
    - echo "Creating Windows artifact"
    - cd ./test && pyinstaller --onedir main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/build/main/*.exe
    when: always
    expire_in: 2 week
