windows_bin:
  stage: deploy
  image:
    name: batonogov/pyinstaller-windows:latest
    entrypoint: ['']
  script:
    - echo "Creating Windows artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onedir main.py
    - cp ./build/main/*.exe ../
  rules:
    - when: always
  artifacts:
    paths:
      - '*.exe'
    when: always
    expire_in: 2 week

linux_bin:
  stage: deploy
  image:
    name: batonogov/pyinstaller-linux:latest
    entrypoint: ['']
  script:
    - echo "Creating Linux artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onedir main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/build/main/*
    when: always
    expire_in: 2 week

linux_slim_bin:
  stage: deploy
  image:
    name: batonogov/pyinstaller-linux:latest-slim
    entrypoint: ['']
  script:
    - echo "Creating Linux artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onedir main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/build/main/*
    when: always
    expire_in: 2 week

osx_bin:
  stage: deploy
  image:
    name: batonogov/pyinstaller-osx:latest
    entrypoint: ['']
  script:
    - echo "Creating OSX artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onedir main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/build/main/*
    when: always
    expire_in: 2 week
