name: Docker Image CI Linux docker.io

on:
  push:
    tags:
      - v*.*.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./Dockerfile-py3-linux-slim
          platforms: |
            linux/i386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-slim
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:latest-slim

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./Dockerfile-py3-linux
          platforms: |
            linux/i386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:latest
